-- MySQL Script generated by MySQL Workbench
-- 04/20/16 00:42:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema carros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carros` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `carros` ;

-- -----------------------------------------------------
-- Table `carros`.`caracteristicas_auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`caracteristicas_auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_caracteristica` INT NULL,
  `id_auto` INT NULL,
  `descripcion` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `carros`.`auto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(45) NULL,
  `marca` VARCHAR(50) NULL,
  `modelo` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_auto_caracteristicas_auto`
    FOREIGN KEY (`id`)
    REFERENCES `carros`.`caracteristicas_auto` (`id_auto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carros`.`tipo_caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`tipo_caracteristica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carros`.`caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`caracteristica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_caracteristica_tipo_caracteristica1_idx` (`id` ASC),
  CONSTRAINT `fk_caracteristica_caracteristicas_auto1`
    FOREIGN KEY (`id`)
    REFERENCES `carros`.`caracteristicas_auto` (`id_caracteristica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caracteristica_tipo_caracteristica1`
    FOREIGN KEY (`id`)
    REFERENCES `carros`.`tipo_caracteristica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carros`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carros`.`calificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_auto` INT NULL,
  `id_usuario` INT NULL,
  `fecha`  NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_calificacion_auto1_idx` (`id_auto` ASC),
  CONSTRAINT `fk_calificacion_auto1`
    FOREIGN KEY (`id_auto`)
    REFERENCES `carros`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
